-- Insert student assignments into pending_student_assignments for Bus 13
insert into public.pending_student_assignments (email, full_name, register_number, bus_id, status)
select * from (values
  ('mohammedsadiq@karunya.edu.in', 'MOHAMMED SADIQ A', 'URK23AE1016', (select id from public.buses where bus_number = '13'), 'active'),
  ('sanfiabegumm@karunya.edu.in', 'SANFIA BEGUM M', 'URK25RA3013', (select id from public.buses where bus_number = '13'), 'active'),
  ('jayashree@karunya.edu.in', 'JAYA SHREE B', 'URK26CS9101', (select id from public.buses where bus_number = '13'), 'active'),
  ('jeevithans@karunya.edu.in', 'JEEVITHAN S', 'URK26CS9063', (select id from public.buses where bus_number = '13'), 'active'),
  ('sooryaprakash@karunya.edu.in', 'SOORYAPRAKASH SENTHILKUMAR', 'URK26RA3008', (select id from public.buses where bus_number = '13'), 'active'),
  ('harshithav@karunya.edu.in', 'HARSHITHA V', 'URK25FS1021', (select id from public.buses where bus_number = '13'), 'active'),
  ('annamoles@karunya.edu.in', 'ANNAMOLE S', 'URK26AE4004', (select id from public.buses where bus_number = '13'), 'active'),
  ('muntasirn@karunya.edu.in', 'MUNTASIR N', 'URK26AI1070', (select id from public.buses where bus_number = '13'), 'active'),
  ('prajiths26@karunya.edu.in', 'PRAJITH S', 'URK26CS7147', (select id from public.buses where bus_number = '13'), 'active'),
  ('harisiddarth@karunya.edu.in', 'HARI SIDDARTH L', 'URK24RA4012', (select id from public.buses where bus_number = '13'), 'active'),
  ('rinuc@karunya.edu.in', 'RINU C R', 'PRK25TZ2011', (select id from public.buses where bus_number = '13'), 'active'),
  ('aleenavincent@karunya.edu.in', 'ALEENA VINCENT KUMAR', 'URK26AI1131', (select id from public.buses where bus_number = '13'), 'active'),
  ('alwinvincent@karunya.edu.in', 'ALWIN VINCENT KUMAR', 'URK26AE4018', (select id from public.buses where bus_number = '13'), 'active'),
  ('danniemac@karunya.edu.in', 'DANNIE MAC MILAN A.R.', 'URK26CS1198', (select id from public.buses where bus_number = '13'), 'active'),
  ('fayazn@karunya.edu.in', 'FAYAZ N', 'URK25CS1087', (select id from public.buses where bus_number = '13'), 'active'),
  ('guruprasathv@karunya.edu.in', 'GURU PRASATH V', 'URK23ME6019', (select id from public.buses where bus_number = '13'), 'active'),
  ('jelingifta@karunya.edu.in', 'JELIN GIFTA C', 'URK23EC1002', (select id from public.buses where bus_number = '13'), 'active'),
  ('joelmichel@karunya.edu.in', 'JOEL MICHEL AUSTIN M', 'URK26DS5014', (select id from public.buses where bus_number = '13'), 'active'),
  ('jonesinfant@karunya.edu.in', 'JONES INFANT A', 'URK23CS5045', (select id from public.buses where bus_number = '13'), 'active'),
  ('meghajacintha@karunya.edu.in', 'MEGHA JACINTHA D', 'URK25BM2010', (select id from public.buses where bus_number = '13'), 'active'),
  ('mmohammed24@karunya.edu.in', 'MOHAMMED MANAS M', 'URK24BM1009', (select id from public.buses where bus_number = '13'), 'active'),
  ('mukundr@karunya.edu.in', 'MUKUND R', 'URK26AE4009', (select id from public.buses where bus_number = '13'), 'active'),
  ('samuela24@karunya.edu.in', 'SAMUEL A', 'URK24CE9002', (select id from public.buses where bus_number = '13'), 'active'),
  ('sibichakravarthi@karunya.edu.in', 'SIBI CHAKRAVARTHI S S', 'URK25EC7027', (select id from public.buses where bus_number = '13'), 'active'),
  ('sylviam@karunya.edu.in', 'SYLVIA M', 'URK25CS1233', (select id from public.buses where bus_number = '13'), 'active'),
  ('varunnandha@karunya.edu.in', 'VARUN NANDHA', 'URK26CS6060', (select id from public.buses where bus_number = '13'), 'active'),
  ('sugeethakirubalini@karunya.edu.in', 'SUGEETHA KIRUBALINI S', 'PRK25FP2014', (select id from public.buses where bus_number = '13'), 'active'),
  ('chrisleonard@karunya.edu.in', 'CHRIS LEONARD C', 'URK26FP2009', (select id from public.buses where bus_number = '13'), 'active'),
  ('harshansivas@karunya.edu.in', 'HARSHANSIVA S.N', 'URK23CS7145', (select id from public.buses where bus_number = '13'), 'active'),
  ('harshithaap@karunya.edu.in', 'HARSHITHAA P S', 'URK25CS7143', (select id from public.buses where bus_number = '13'), 'active'),
  ('jaslindavison@karunya.edu.in', 'JASLIN DAVISON', 'URK25BT5012', (select id from public.buses where bus_number = '13'), 'active'),
  ('ranjithb@karunya.edu.in', 'RANJITH B', 'PRK25MS1009', (select id from public.buses where bus_number = '13'), 'active'),
  ('vigneshkumar26@karunya.edu.in', 'VIGNESH KUMAR S', 'URK26CS7152', (select id from public.buses where bus_number = '13'), 'active'),
  ('liwyakarolin@karunya.edu.in', 'LIWYA KAROLIN B', 'URK26DS3032', (select id from public.buses where bus_number = '13'), 'active'),
  ('abishekfranklin@karunya.edu.in', 'ABISHEK FRANKLIN A', 'URK23CS7077', (select id from public.buses where bus_number = '13'), 'active'),
  ('sherwingladstan@karunya.edu.in', 'V SHERWIN GLADSTAIN', 'URK26DS5029', (select id from public.buses where bus_number = '13'), 'active'),
  ('dominicraja@karunya.edu.in', 'DOMINIC RAJA M S', 'URK23CS1006', (select id from public.buses where bus_number = '13'), 'active'),
  ('gowthamk23@karunya.edu.in', 'GOWTHAM K', 'URK23AI1012', (select id from public.buses where bus_number = '13'), 'active'),
  ('sharmis25@karunya.edu.in', 'SHARMI S', 'URK25AI1060', (select id from public.buses where bus_number = '13'), 'active'),
  ('ariesnathya@karunya.edu.in', 'ARIES NATHYA A', 'URK23AI1082', (select id from public.buses where bus_number = '13'), 'active'),
  ('hemathrib@karunya.edu.in', 'HEMATHRI B S', 'URK23AI1102', (select id from public.buses where bus_number = '13'), 'active'),
  ('areenashafra@karunya.edu.in', 'AREENA SHAFRA A', 'URK26AI1150', (select id from public.buses where bus_number = '13'), 'active'),
  ('ajaykumar26@karunya.edu.in', 'AJAY KUMAR R S', 'URK26CS1108', (select id from public.buses where bus_number = '13'), 'active'),
  ('jairamb@karunya.edu.in', 'JAIRAM B S', 'URK26EE1006', (select id from public.buses where bus_number = '13'), 'active'),
  ('mohammedarief@karunya.edu.in', 'MOHAMMED ARIEF', 'URK26AE1034', (select id from public.buses where bus_number = '13'), 'active'),
  ('alvinsylvester@karunya.edu.in', 'ALVIN SYLVESTER I', 'URK26CS1207', (select id from public.buses where bus_number = '13'), 'active')
) as t(email, full_name, register_number, bus_id, status)
on conflict (email) do update set
  full_name = excluded.full_name,
  register_number = excluded.register_number,
  bus_id = excluded.bus_id,
  status = excluded.status;

-- Update existing profile records for these students directly
update public.profiles
set
  bus_id = (select id from public.buses where bus_number = '13'),
  status = 'active'
where lower(email) in (
  'mohammedsadiq@karunya.edu.in',
  'sanfiabegumm@karunya.edu.in',
  'jayashree@karunya.edu.in',
  'jeevithans@karunya.edu.in',
  'sooryaprakash@karunya.edu.in',
  'harshithav@karunya.edu.in',
  'annamoles@karunya.edu.in',
  'muntasirn@karunya.edu.in',
  'prajiths26@karunya.edu.in',
  'harisiddarth@karunya.edu.in',
  'rinuc@karunya.edu.in',
  'aleenavincent@karunya.edu.in',
  'alwinvincent@karunya.edu.in',
  'danniemac@karunya.edu.in',
  'fayazn@karunya.edu.in',
  'guruprasathv@karunya.edu.in',
  'jelingifta@karunya.edu.in',
  'joelmichel@karunya.edu.in',
  'jonesinfant@karunya.edu.in',
  'meghajacintha@karunya.edu.in',
  'mmohammed24@karunya.edu.in',
  'mukundr@karunya.edu.in',
  'samuela24@karunya.edu.in',
  'sibichakravarthi@karunya.edu.in',
  'sylviam@karunya.edu.in',
  'varunnandha@karunya.edu.in',
  'sugeethakirubalini@karunya.edu.in',
  'chrisleonard@karunya.edu.in',
  'harshansivas@karunya.edu.in',
  'harshithaap@karunya.edu.in',
  'jaslindavison@karunya.edu.in',
  'ranjithb@karunya.edu.in',
  'vigneshkumar26@karunya.edu.in',
  'liwyakarolin@karunya.edu.in',
  'abishekfranklin@karunya.edu.in',
  'sherwingladstan@karunya.edu.in',
  'dominicraja@karunya.edu.in',
  'gowthamk23@karunya.edu.in',
  'sharmis25@karunya.edu.in',
  'ariesnathya@karunya.edu.in',
  'hemathrib@karunya.edu.in',
  'areenashafra@karunya.edu.in',
  'ajaykumar26@karunya.edu.in',
  'jairamb@karunya.edu.in',
  'mohammedarief@karunya.edu.in',
  'alvinsylvester@karunya.edu.in'
);
